FROM amazoncorretto:21-alpine
# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from your host to the container
COPY target/client-0.0.1-SNAPSHOT.jar /app/

# Expose the port that your Spring Boot application listens on (default is 8080)
EXPOSE 8080

# Define the command to run your Spring Boot application when the container starts
CMD ["java", "-jar", "client-0.0.1-SNAPSHOT.jar"]