version: '3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: k8sDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  server:
    image: server:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/k8sDb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_PORT: 8080
  client:
    image: client:1.0.0
    ports:
      - "8081:8081"
    depends_on:
      - server
    environment:
      SERVER_URL: http://server:8080
      SERVER_PORT: 8081