spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/k8sDb
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080