apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/persistent/app1 # Path on the host where the data will be stored -> create that path in minikube cluster -> minikube ssh -> mkdir path